export const data = [
	{
		"#": "1",
		"CountryCode": "KE",
		"Country": "Kenya",
		"City": "Marsabit",
		"PortraitPhoto": "",
		"Firstname": "Benjamin",
		"Lastname": "Galwaha",
		"Job": "Farmer and shopkeeper",
		"Quote": "“I worry so much about the drought and the low prices for our livestock.”",
		"LinkedArticle": "https://www.thenewhumanitarian.org/node/260983/",
		"QuoteDate": "2019-07-31",
		"QuotePhoto": "https://images.thenewhumanitarian.org/2019/africa-drought/quote-benjamin.png",
		"QuoteVideo": "https://www.youtube.com/watch?v=DHM7rZtF9gw"
	},
	{
		"#": "2",
		"CountryCode": "KE",
		"Country": "Kenya",
		"City": "Nkoroi",
		"PortraitPhoto": "",
		"Firstname": "Marlvin",
		"Lastname": "Maura",
		"Job": "Butcher",
		"Quote": "\"My biggest worry is for my kid to go to school. Her education is my priority\"",
		"LinkedArticle": "https://www.thenewhumanitarian.org/",
		"QuoteDate": "2019-07-31",
		"QuotePhoto": "https://images.thenewhumanitarian.org/2019/africa-drought/quote-marlvin.png",
		"QuoteVideo": "https://www.youtube.com/watch?v=DHM7rZtF9gw"
	},
	{
		"#": "5",
		"CountryCode": "SM",
		"Country": "Somalia",
		"City": "Mogadishu",
		"PortraitPhoto": "",
		"Firstname": "Madina",
		"Lastname": "Yacoub",
		"Job": "Domestic worker",
		"Quote": "\"Maybe one month you earn more money than you expected, life doesn't stand still.\"",
		"LinkedArticle": "https://www.thenewhumanitarian.org/",
		"QuoteDate": "1/8/2019",
		"QuotePhoto": "https://images.thenewhumanitarian.org/2019/africa-drought/quote-madina.png",
		"QuoteVideo": ""
	},
	{
		"#": "3",
		"CountryCode": "ZM",
		"Country": "Zimbabwe",
		"City": "Harare metro",
		"PortraitPhoto": "",
		"Firstname": "Ganda",
		"Lastname": "Farayi",
		"Job": "Forklift operator",
		"Quote": "\"Our money can’t buy compared to when we were officially using the US dollar during the government of national unity.\"",
		"LinkedArticle": "",
		"QuoteDate": "",
		"QuotePhoto": "https://images.thenewhumanitarian.org/2019/africa-drought/quote-ganda.png",
		"QuoteVideo": ""
	},
	{
		"#": "4",
		"CountryCode": "ZM",
		"Country": "Zimbabwe",
		"City": "Seke district",
		"PortraitPhoto": "",
		"Firstname": "Loveness",
		"Lastname": "January",
		"Job": "First aid officer",
		"Quote": "\"We have stopped buying essentials like sugar so that we buy cooking oil and at least eat relish prepared with oil.\"",
		"LinkedArticle": "",
		"QuoteDate": "",
		"QuotePhoto": "https://images.thenewhumanitarian.org/2019/africa-drought/quote-loveness.png",
		"QuoteVideo": ""
	},
	{
		"#": "6",
		"CountryCode": "SM",
		"Country": "Somalia",
		"City": "Mogadishu",
		"PortraitPhoto": "",
		"Firstname": "Aadan",
		"Lastname": "Mohammed",
		"Job": "Labourer/IDP",
		"Quote": "\"Everything is expensive, food and even water. Prices in the market keep going up.\" ",
		"LinkedArticle": "https://www.thenewhumanitarian.org/",
		"QuoteDate": "1/8/2019",
		"QuotePhoto": "https://images.thenewhumanitarian.org/2019/africa-drought/quote-aadan.png",
		"QuoteVideo": ""
	}
]