# This is a basic workflow to help you get started with Actions
name: Build and Deploy React App via FTP

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the `main` branch
on:
  push:
    branches: [main, staging]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-and-deploy"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Runs a single command using the runners shell
      - name: Run react build script
        run: yarn && yarn build
        env:
          CI: false

      - name: List output files
        run: find build/ -print

      - name: 📂 Sync files to production
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        if: github.ref == 'refs/heads/main'
        with:
          server: ftp.fahrenheit.sui-inter.net
          username: tnh
          password: bre5mgc4dtw1gjc@EVE
          local-dir: build/
          server-dir: embeddables/

      - name: 📂 Sync files to staging
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        if: github.ref == 'refs/heads/staging'
        with:
          server: ftp.fahrenheit.sui-inter.net
          username: tnh
          password: bre5mgc4dtw1gjc@EVE
          local-dir: build/
          server-dir: embeddables/
