name: Build and Deploy React App via FTP

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main, staging]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Run react build script
        working-directory: ./
        run: yarn && yarn build
        env:
          CI: false

      - name: List output files
        run: find build/ -print

      - name: 📂 Sync files to production
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ftp.fahrenheit.sui-inter.net
          username: tnh
          password: bre5mgc4dtw1gjc@EVE
          local-dir: build/
          server-dir: embeddables/
          if: github.ref == 'refs/heads/main'

      - name: 📂 Sync files to staging
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ftp.fahrenheit.sui-inter.net
          username: tnh
          password: bre5mgc4dtw1gjc@EVE
          local-dir: build/
          server-dir: embeddables/
          if: github.ref == 'refs/heads/staging'